# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/

initContainers:
  - name: friendly-umbrella-init
    image: 
      repository: friendly-umbrella
      pullPolicy: IfNotPresent
      tag: "latest"
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: "django_application.settings.helm_eks"
    commands: ["sh", "-c"]
    args:
    - | 
      python manage.py makemigrations && python manage.py migrate

containers:
  - name: friendly-umbrella
    image: 
      repository: friendly-umbrella
      pullPolicy: IfNotPresent
      tag: "latest"
    env:
    - name: DJANGO_SETTINGS_MODULE
      value: "django_application.settings.helm_eks"

image:
  repository: friendly-umbrella
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8000

serviceAccount:
  create: false
  name: service-account-name

config:
  AWS_STORAGE_BUCKET_NAME: bucket_name
  RDS_HOST: host
  RDS_PORT: port
  RDS_USER: user
  RDS_PASSWORD: password
  RDS_DB_NAME: db

mapping:
  enabled: true
  host: "friendly-umbrella.localhost"
  ambassador_id:
    - "--apiVersion-v3alpha1-only--default"
  prefix: "/"
