# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: friendly-umbrella
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8000

serviceAccount:
  create: false
